language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - npm run bootstrap

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "stable"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
